# Neue Linux-Kernel abrufen
- name: Neueste installierte Kernel-Version abrufen
  shell: 'ls -1 /boot/vmlinuz-* | sort -V | tail -n 1 | sed "s/\/boot\/vmlinuz-//"'
  register: latest_kernel
  changed_when: false
  become: true

# Debug-Ausgabe für das Kernel-Update
- name: Kernel-Update-Meldung
  debug:
    msg: Linux-Kernel wurde von {{ current_kernel.stdout }} auf {{ latest_kernel.stdout }} updatet
  when: current_kernel.stdout != latest_kernel.stdout
  become: true

# Linux Debian neuestarten
- name: Linux-Kernel wurde auf {{ latest_kernel.stdout }} updatet. VM wird neu gestartet.
  ansible.builtin.reboot:
    reboot_timeout: 60 # Wie lange Ansible warten soll, bevor der Maschine neuestartet 
  when: current_kernel.stdout != latest_kernel.stdout
  become: true
