---
# Linux Kernel-Version speichern
- name: Aktuelle Kernel-Version abrufen
  shell: "uname -r"
  register: current_kernel
  changed_when: false
  become: true

# Linux Debian Updat installieren
- name: Update Paketlisten
  ansible.builtin.apt:
    update_cache: yes
  become: true
